### ISSUE TITLE
Open Package.swift release

### ISSUE THREAD

**Issue by nickkaczmarek** [macecchi/xcopen#4]
Hey,

I noticed that you had accepted a pull request that enables opening `Package.swift`, but this update doesn't seem to have been released or in Homebrew. Is there anyway you can release that so I can use that feature?

**Comment by Tyler-Keith-Thompson** [comment]
Bump @macecchi can you cut a release?

**Comment by nickkaczmarek** [comment]
@Tyler-Keith-Thompson I ended up using the xcopen from Erica Sadun.

https://github.com/erica/xcopen
